name: ADF Workflow Test
on: 
  push:
    branches:
      - main
      - adf_publish
jobs:
  DeployStaging:
    runs-on: ubuntu-latest
    steps:
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 
    - name: data-factory-staging-deploy
      uses: Azure/data-factory-deploy-action@v1.1.0
      with:
        resourceGroupName: rg-github-actions-test
        dataFactoryName: adf-staging-njl
